marvel_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from marvel_inventory.forms import UserLoginForm
from marvel_inventory.models import User, db, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            username = form.username.data
            print(email, password, username)

            user = User(email, password = password, username = username)

            db.session.add(user)
            db.session.commit()
            flash(f"You have successfully created a user account {username}", 'user-created')
            
            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            username = form.username.data
            print(email, password, username)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password was incorrect.', 'auth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception("Invalid Form Data or User Does Not Exist: please check your form or sign up!")
    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

marvel_inventory/site/routes.py
from flask import Blueprint, render_template

"""
Note that in the below code,
some arguments are specified when creating the Blueprint object.
The first argument, 'site' is the blueprint's name which is used
by Flask's routing mechanism

The second argumnet, __name__, is the Blueprint's import name,
which Flask uses to locate the Blueprint's resources
"""

site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

marvel_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>The Marvel Museum</title>
</head>
<body>
    <!-- Nav Bar Here -->
    <nav class = "ct-nav">
        <div>
            <img src = "../static/images/marvel.png" id = "Marvel_Logo"> 
        </div>
    <!-- Nav Items -->
    <div>
        <ul id = "horizontal-list">
            <a href="{{ url_for('site.home') }}">
                <li>The Marvel Museum</li>
            </a>
            <a href="https://stanleefoundation.org/donate-today/">
                <li>Donate</li>
            </a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('site.profile') }}">
                <li>Profile</li>
            </a>
            <a href="{{ url_for('auth.logout') }}">
                <li>Log Out</li>
            </a>
            {% else %}
            <a href="{{ url_for('auth.signin') }}">
                <li>Sign In</li>
            </a>
            <a href="{{ url_for('auth.signup') }}">
                <li>Sign Up</li>
            </a>
            {% endif %}
           
        </ul>
    </div>    
    </nav>
    <!-- End of Nav -->
    {% block content %}

    {% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

marvel_inventory/templates/forms.html
<form method = 'POST'>
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Enter your username here: ") }}
        </fieldset> 
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter your email here: ") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter your password here: ") }}
        </fieldset>
    
        {{ form.submit_button(class = "btn-btn-danger btn-block") }}
    </div>

</form>